9조 FE 코드리뷰 2회차
kakao-tech-campus-2nd-step3/Team9_FE pull request #16
Opened 2024-09-27 14:45 UTC by joojjang

## **PR**

### ✨ 작업 내용
 #5 #9 

- 지난 주에 이어서 환경 구축 마저 했습니다. 
- 공통 컴포넌트 중 일부를 구현하였습니다. (Chip, CategoryTabs, Tumbnail 등)

---

### ✨ 참고 사항

- 당초 계획보다 조금 개발이 늦어지고 있지만 주말 내로 공통 컴포넌트 제작하고 다음 주에는 페이지 구현 들어가려고 합니다!
- 다음 주부터 피어 리뷰 후 머지하겠습니다 ㅜㅜ

---

### 질문

1. category tabs 안에 category tab element를 만들었습니다.  
이때 tab의 크기를 정하고 넣으니깐 알아서 category tab element들이 width가 줄어들던데,  
category tab element들의 크기도 정해줬는데 이렇게 자동으로 줄어드는 이유가 무엇인지 궁금합니다.  
  
display: flex와 관련있다 생각했었는데 block이나 relative를 해줘도 그대로였던 걸 알았습니다.  
그래서 생각해보니 이 display는 요소의 배치에 관여한다는게 생각이 났습니다.  
그렇다면 자동으로 줄어드는 이유는 단순히 부모의 크기(category tab)가 정해져있어서인 건가요?

2. 1번 질문과 이어집니다.  
혹시 이런 비슷한 요소에서 크기가 다를 경우에는 ArtistItem처럼 다루면 될까요?  
이유는 모르겠는데 1번 질문에 했던것 처럼 Thumbnail이 줄지 않아서 이 경우에는 width를 %로 맞춰놓고 두 개를 만들어 주었습니다!!  

3. import styled를 입력하면 자동 완성으로 from "@emotion/styled/macro"가 나오는데,  
@emotion/styled를 사용하고 싶은데 이건 안 뜨고 왜 macro 붙은 것만 뜨는지 알 수 있을까요?  

### ✏ Git Close

2024-09-28 09:44 UTC, yujo11 requested changes
안녕하세요 ~ 

진행 된 내용이 많지 않아 간단한 코멘트들만 남겼는데 확인 해주시면 좋을거 같습니다 ~!

>관리해야 하는 페이지 개수가 많아 pages 폴더가 복잡한데, 상품 관련이면 상품, 계정 관련이면 계정, ...
이런 식으로 중간에 폴더를 하나 더 두고 분류하는 게 좋을까요?

저는 같은 관심사를 가진 파일들은 묶어서 관리하면 좋을거라고 생각합니다. 

채널 통해서 공유드린 FSD 관련 글들도 한 번 읽어보시면서 참고해보셔도 좋을거 같네요

>깃 브랜치 중 Weekly 브랜치를 개발 환경으로(dev 브랜치처럼) 이용하고, Master를 프로덕션 환경, Review를 리뷰 브랜치로 두어 3개의 브랜치만 관리하고, Develop 브랜치는 삭제해도 될까요? 브랜치 종류가 많고 관리하기 힘들어서요.

브랜치 전략은 정답이 정해져 있는게 아니니 상황에 맞게 편하신 방법을 사용하시면 될거 같습니다 ㅎㅎ

>category tabs 안에 category tab element를 만들었습니다.
이때 tab의 크기를 정하고 넣으니깐 알아서 category tab element들이 width가 줄어들던데,
category tab element들의 크기도 정해줬는데 이렇게 자동으로 줄어드는 이유가 무엇인지 궁금합니다.

자식 요소들 크기의 합이 부모요소의 크기를 초과하는 경우에 display가 flex로 설정되어 있어 부모의 제약조건에 따라 조정되어 그러는거 같아요

>혹시 이런 비슷한 요소에서 크기가 다를 경우에는 ArtistItem처럼 다루면 될까요?

이건 어떤걸 물어보시는건지 잘 이해하지 못 헀는데 조금 더 자세하게 설명해주시면 좋을거 같아요

>import styled를 입력하면 자동 완성으로 from "@emotion/styled/macro"가 나오는데,
@emotion/styled를 사용하고 싶은데 이건 안 뜨고 왜 macro 붙은 것만 뜨는지 알 수 있을까요?

레포지토리를 클론 받아 아무런 설정도 건드리지 않고 제 local 환경에서 실행 했을 때는 `@emotion/styled`가 먼저 나오네요.

팀원 모두 같은 현상을 겪고 있나요? 로컬 IDE 환경을 점검해보시면 좋을거 같아요

<img width="696" alt="image" src="https://github.com/user-attachments/assets/ca72d4bb-0fbf-4bd8-9db4-7b2512f4723a">

---

이번 주도 고생 많으셨습니다 ㅎㅎ 코멘트 확인하고 다시 리뷰요청 부탁드려요 ~~

2024-09-28 09:44 UTC, yujo11 commented on index.html
> +<html lang="ko">
👍 👍 👍

2024-09-28 09:44 UTC, yujo11 commented on index.html
> +    <link rel="stylesheet" href="src/styles/reset.css" />
`reset.css`는 여기에서 import하는 이유가 있나요?

2024-09-28 09:44 UTC, yujo11 commented on index.html
>    <head>
`<head>` 안에 어떤 태그들이 들어가는지 찾아보시고 적절하게 변경해보셔도 좋을거 같네요 ㅎㅎ

2024-09-28 09:44 UTC, yujo11 commented on src/components/Thumbnail.tsx
> +  return <Wrapper></Wrapper>;
내부에 사용하는 요소가 없는 경우 self-closing tag를 활용해보시면 좋겠네요
```suggestion
  return <Wrapper />
```

2024-09-28 09:44 UTC, yujo11 commented on src/styles/variables.css
👍 👍 👍

2024-09-28 09:44 UTC, yujo11 commented on src/routes/index.tsx
> +        children: [
react-router-dom에서 제공되는 `<Outlet/>`을 사용하여 Layout을 만들어 적용하면 중복 코드를 많이 없앨 수 있을거 같네요

2024-09-28 09:44 UTC, yujo11 commented on src/routes/index.tsx
> +import Signup from '@/pages/Signup';
앞으로 생성 될 페이지가 많아 보이는데 dynamic routing을 적용해보면 어떨까요?

2024-09-28 10:19 UTC, seung365 commented on index.html
> +    <link rel="stylesheet" href="src/styles/reset.css" />
이걸 해줘야 reset.css가 적용된다고 생각했었는데 그렇지 않는거 같아 지우도록 하겠습니다!

2024-09-28 10:20 UTC, seung365 commented on src/components/Thumbnail.tsx
> +  return <Wrapper></Wrapper>;
넵 수정하도록 하겠습니다!

2024-09-28 10:40 UTC, joojjang commented on index.html
> +    <link rel="stylesheet" href="src/styles/reset.css" />
자바스크립트 시작점인 main.tsx에 연결해도 되지만 css 초기화 파일이기 때문에 body 태그보다 먼저 적용되게 하기 위해 해당 위치에 삽입하였습니다.

2024-09-29 23:57 UTC, seung365 commented on index.html
>    <head>
넵~!

2024-09-30 08:49 UTC, merged