Weekly6
kakao-tech-campus-2nd-step3/Team9_FE pull request #39
Opened 2024-10-11 09:16 UTC by joojjang

## **PR**

### ✨ 작업 내용

- 

### 📌 참고 사항

-

### 🐞 현재 버그

-

### 🧐 질문

-

2024-10-12 09:30 UTC, yujo11 requested changes
안녕하세요~  

이번 주는 코드 레벨에서 남길 리뷰가 많지 않았네요

현재 에러 상황에서 가장 의심되는건 파일의 형식인데요. JSX 문법을 사용하고 있지만 파일 형식이 `.ts`로 보여요. 파일 형식을  `.tsx`로 바꾸고 다시 시도해보시면 좋을거 같네요

이번 주도 고생 많으셨습니다 ~~ ㅎㅎ

2024-10-12 09:30 UTC, yujo11 commented on src/components/Footer/index.tsx
> +// styles
이런 주석은 불필요하게 느껴지네요 ㅎㅎ

2024-10-12 09:30 UTC, yujo11 commented on src/styles/variables.css
> +  --color-gray-deep: #909090;
오 이름이 직관적으로 변경됐네요 ㅎㅎ

아무거나 검색해서 하나 가져왔는데 아래처럼 숫자를 이용해 variant를 나누는 방법도 많이 사용되니 참고하시면 좋을거 같습니다! (변경하라는 뜻은 아닙니다)

<img width="783" alt="image" src="https://github.com/user-attachments/assets/6630c6f2-e3d8-4487-831c-fa265217acde">

2024-10-12 13:12 UTC, joojjang commented
리뷰 해주신 부분들 반영했습니다. 
질문했던 문제도 tsx 구조인데 ts여서 그런 거더라고요. 확장자 바꾸었더니 오류 안 뜹니다. 감사합니다~~

※ 리뷰 주신 것 외에 리팩토링한 부분:
- components 아래 폴더 구조 정리
- 컬러 변수 네이밍 직관적이어서 좋다 하셨는데, medium 다 쓰기 번거로워서 약어로 md 이런 식으로 바꾸었습니다😅
- lint 설정 파일 수정
- 이외 ...

2024-10-12 15:09 UTC, yujo11 requested changes

2024-10-12 15:09 UTC, yujo11 commented on .eslintrc.js
> +      },
이건 어떤 목적으로 작성된 코드들일까요? 눈으로 보는걸로는 유추가 잘 되지 않아 질문 남깁니다 ㅎㅎ

2024-10-12 15:09 UTC, yujo11 commented on src/constants/TabList.tsx
> +const TabList = [
특정한 형태로 작성되어야 한다면 여기는 typescrtip를 통해 타입을 지정하면 좋을거 같아요 
```suggestion
// ex)
const TabList: { lable, defaailicont ... } " { ... } = [
```

2024-10-13 03:05 UTC, joojjang commented on .eslintrc.js
> +      },
import sort 설정을 한 건데, 위에서부터 차례대로 빌트인 모듈이나 패키지, 프로젝트 내에서 설정한 절대경로, 상대경로, ... 순입니다.
구글링해서 블로그 참고하고 챗지피티 참고해서 조합해놓았습니다! (근데 파일 저장 시 자동으로 솔팅이 되어야 하는데 안 돼서.. 다른 부가 설정 시도 중이었습니다)

2024-10-13 03:55 UTC, yujo11 approved these changes
고생 하셨습니다 ~~

2024-10-13 03:55 UTC, yujo11 commented on .eslintrc.js
> +      },
아하 그렇군요

[eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)의 `import/order` 설정을 많이 이용하는데 이걸로 한번 해보셔도 좋을거 같아요

2024-10-13 03:55 UTC, merged