[7주차]
kakao-tech-campus-2nd-step3/Team9_FE pull request #60
Opened 2024-10-18 09:20 UTC by joojjang

## **PR**

### ✨ 작업 내용

- 홈 페이지 구현
- 검색 부분 일부 구현
- 지난 주에 여쭤봤던 레이아웃 (플로팅 버튼 위치ㅠㅠ) 고쳤습니다!

### 📌 참고 사항

-

### 🐞 현재 버그

- 스크롤 내리면 scroll to top 버튼이 떠야 하는데 안 뜹니다😅

### 🧐 질문

-

2024-10-19 07:17 UTC, yujo11 requested changes
안녕하세요 ~

개발 진행하느라 고생 많으셨습니다 ㅎㅎ

코멘트들 남겼으니 확인 부탁드려요 ~

2024-10-19 07:17 UTC, yujo11 commented on src/components/common/FakeSearchBar/index.tsx
> +const FakeSearchBar = ({ modalOpen }: FakeSearchBarProps) => {
오 `Fake`는 무슨 의미로 붙은건가요?

2024-10-19 07:17 UTC, yujo11 commented on src/components/common/FakeSearchBar/index.tsx
> +const FakeSearchBar = ({ modalOpen }: FakeSearchBarProps) => {
`common/` 폴더 하위에 위치하고 있지만 placeholder나 prop을 보면 특정 위치에서 특정 목적으로만 사용될거 같은데요. 

위치가 적절한지 고민해보셔도 좋을거 같아요

2024-10-19 07:17 UTC, yujo11 commented on src/components/common/SearchModal/RecentSearch.tsx
> +    localStorage.removeItem('searchArray');
`searchArray`처럼 key값으로 사용되는 값들은 상수로 만들어서 사용하시면 좋을거 같아요

2024-10-19 07:17 UTC, yujo11 commented on src/components/common/SearchModal/RecentSearch.tsx
> +        ))}
`item`에는 key로 사용할만한 값이 없나요?

2024-10-19 07:17 UTC, yujo11 commented on src/components/layouts/FAB/index.tsx
> +  }, [scrollContainerRef]);
이 부분이 PR 본문에 적어주신 코드가 복잡해졌다고 말씀하신 부분 같은데요.

코드를 보다 읽기 쉽게 만들려면 어떻게 해볼 수 있을까요?

2024-10-19 07:17 UTC, yujo11 commented on src/components/layouts/SearchBar/index.tsx
> +          }}
`keyDown`과 `keyUp`이 어떻게 다른지 한번 찾아보시고 어느 이벤트가 더 적절한지 고민해보셔도 좋을거 같아요

2024-10-19 07:17 UTC, yujo11 commented on src/components/layouts/SearchBar/index.tsx
> +  };
`form`으로 처리하지 않고 keyboardEvent를 사용하신 이유가 있을까요?

2024-10-19 07:17 UTC, yujo11 commented on src/pages/SearchResults/index.tsx
> +    navigate(-1);
이전 페이지로 이동하기 위해 많이 사용하는 방법이지만 유저가 예상한 플로우 외에 해당 페이지에 url로 직접 접근했을 때 누르면 동작이 어떻게 될지도 한번쯤 생각해보시면 좋을거 같네요 ㅎㅎ

2024-10-19 07:21 UTC, seung365 commented on src/components/common/FakeSearchBar/index.tsx
> +const FakeSearchBar = ({ modalOpen }: FakeSearchBarProps) => {
이 FakeSearchBar의 경우 search bar의 기능은 하지 않지만 search modal을 띄워줄 수 있는 search 모양이 필요해서 Fake를 붙이긴 했습니다!

2024-10-19 07:22 UTC, seung365 commented on src/components/common/FakeSearchBar/index.tsx
> +const FakeSearchBar = ({ modalOpen }: FakeSearchBarProps) => {
아하 넵 Search Modal 을 띄울 상황이 올 경우 해당 FakeSearchBar을 항상 사용한다 생각해서 두긴 했는데 다른 UI에서 사용하지 않을경우 위치를 옮겨두겠습니다!

2024-10-19 07:29 UTC, seung365 commented on src/components/common/SearchModal/RecentSearch.tsx
> +        ))}
local storage에 최근 검색어를 저장할때 임의로 key를 넣어 줄 수 있을꺼 같습니다. 그 방안으로 하는게 더 좋을까요?

2024-10-19 07:45 UTC, seung365 commented on src/components/layouts/SearchBar/index.tsx
> +  };
form이 익숙하지 않아 생각하지 못했던거 같습니다..! 이부분 반영하여 수정하겠습니다

2024-10-20 11:46 UTC, joojjang commented on src/components/layouts/FAB/index.tsx
> +  }, [scrollContainerRef]);
리팩토링해서 업데이트했습니다~

2024-10-20 11:55 UTC, joojjang commented
#65 
@yujo11 
FAB 코드를 리팩토링했습니다. 
1. 우선 파일을 분리했습니다. 컴포넌트가 여러 개이다보니 코드 자체가 길어져서요 (처음엔 이렇게 길어질 줄 몰랐는데...)
FAB
ㄴindex.tsx (버튼만 모아둠)
ㄴFABContainer.tsx (버튼을 불러와서 사용)
이렇게 두고 실제로 레이아웃에서 불러오는 파일은 FABContainer입니다. 

2. FABContainer에서 useEffect문 안의 코드를 간결하게 하고자 했는데,  
같은 값은 변수 하나로 다 쓰고, 조건문도 반복되어서 하나로 묶었습니다.  

그래도 좀 복잡은 한 것 같지만.. 최대한 줄인 것 같습니다!

2024-10-20 13:52 UTC, yujo11 commented on src/components/common/SearchModal/RecentSearch.tsx
> +        ))}
저는 그 말씀해주신 방향이 좋다고 생각 되네요 ㅎㅎ

2024-10-21 07:43 UTC, merged