[8주차] 9조 FE 코드리뷰 6회차
kakao-tech-campus-2nd-step3/Team9_FE pull request #69
Opened 2024-10-27 15:21 UTC by joojjang

## **PR**

### ✨ 작업 내용

- 로그인 & 회원가입 구현 중이었습니다.
- 로그인은 카카오톡 API 구현이 아직 덜 되었다 해서 보류해두고 화면만 만들었습니다.  
- 회원가입은 회원 유형이 일반 유저/학생 작가/사업자 작가로 구분되어 있는데, 이중 일반 유저, 학생 작가 회원 정보 폼까지 만들었습니다.  
학생 작가는 중간에 학생 인증도 해야 해서 외부 API (univCert라는...) 연동해서 인증 로직 짜놓았습니다.  

### 📌 참고 사항
- 아직 리팩토링이 다 된 상태는 아닌데, StudentSeller1에 학생 인증 관련 코드 너무 길어서 파일 분리를 하려고 합니다. 그게 MVC 패턴에 더 맞을 것 같기도 하고요... 

### 질문
1. Signup 폴더 내 폴더 구조 이렇게 하면 괜찮을지 모르겠어요...
<img width="278" alt="image" src="https://github.com/user-attachments/assets/67873f7a-3e9e-4585-8aaa-337afe5eb14f">

처음에 코드를 너무 복잡하고 더럽게 짜서 알아볼 수 있을 정도로만 리팩토링한다는 게 오래 걸렸습니다ㅜㅜ  
axios -> 탠스택 쿼리로 바꾸고 주스탠드도 깔고 하면서...  
늦어도 토요일 오후에는 올릴 줄 알았는데 죄송합니다😢

2024-11-02 06:02 UTC, yujo11 requested changes
안녕하세요 이번 주도 고생 많으셨습니다 ~

>Signup 폴더 내 폴더 구조 이렇게 하면 괜찮을지 모르겠습니다.

설명을 듣고 보면 크게 어색하게 느껴지는 부분은 없는데요.

한 페이지에서 상태에 따라 여러 분기가 생기는거 같아요 퍼널 방식을 적용하면 복잡도를 줄이고 코드를 관리하는데 도움이 될 수도 있을거 같은데요. 아래 영상 한번 봐보시면 좋을거 같네요 ㅎㅎ

- [[토스ㅣSLASH 23 - 퍼널: 쏟아지는 페이지 한 방에 관리하기](https://www.youtube.com/watch?v=NwLWX2RNVcw&pp=ygUG7Y2864SQ)]

>브라우저에서 CORS 에러가 뜨면 프론트에서 가능한 해결 방법은 프록시 쓰는 법 밖에 없나요?

서버의 수정이 불가능한 상황에서는 프록시 서버를 통해서 api 요청을 하는게 일반적이기는 합니다. 

아래 내용들을 점검해보면 좋을거 같아요

1. 403 에러와 CORS 에러가 동일한 에러가 아닌데 CORS가 발생하고 있는게 맞는지
2. 서버 쪽의 수정이 불가능한 상황인지

---

이번 주도 고생 많으셨습니다 ~~ 👍 👍 👍

2024-11-02 06:02 UTC, yujo11 commented on src/apis/artists/usePostBusinessArtist.ts
> +    if (error.response) {
`axios`를 사용하시는거 같은데 any 대신에 `isAxiosError` 같은 유틸을 사용해 타입을 좁혀서 사용해보셔도 좋을거 같아요

2024-11-02 06:02 UTC, yujo11 commented on src/apis/artists/usePostStudentArtist.ts
> +  }
이런 에러 처리는 `useMuation`에서도 할 수 있고, `mutation`을 하는 컴포넌트에서도 할 수 있는데요.

여러 선택지 중 여기에서 에러 처리를 하게 된 배경을 들어보고 싶네요 ㅎㅎ

2024-11-02 06:02 UTC, yujo11 commented on src/apis/instance/index.ts
> +      refetchOnWindowFocus: true,
이 옵션들은 어떤 의사결정 과정을 통해 들어갔을까요?

2024-11-02 06:02 UTC, yujo11 commented on src/apis/nts-businessman/useVerifyBusiness.ts
> +  };
필드명만 보고는 각각의  필드가 어떤 역할을 하는 parameter인지 알기 어려운데요. 주석을 적절하게 사용해보셔도 좋을거 같네요 ㅎㅎ

2024-11-02 06:02 UTC, yujo11 commented on src/apis/nts-businessman/useVerifyBusiness.ts
> +    console.log('verify response: ', response);
불필요한 코드는 commit 시점에 한번 더 확인하고 제거해보시면 좋을거 같아요

2024-11-02 06:02 UTC, yujo11 commented on src/pages/Login/index.tsx
> +            onClick={() => navigate(`${RouterPath.home}`)}
아래처럼 작성하지 않은 이유가 있나요?

```suggestion
            onClick={() => navigate(RouterPath.home)}
```

2024-11-02 06:02 UTC, yujo11 commented on src/pages/Signup/index.tsx
> +        leftSideChildren={<IconButton icon="arrow-back" onClick={() => navigate(-1)} />} // 카카오톡 로그인 연동되면 수정
이런 주석들은 팀 내 컨벤션을 정해서 남기시면 나중에 이런 TODO 주석들을 한 눈에 확인하기 좋을거 같네요

ex) `// TODO {내용}`

2024-11-02 06:02 UTC, yujo11 commented on src/pages/Signup/progresses/ArtistProgress/StudentArtist/StudentArtist1.tsx
> +    }
`early return`을 사용해서 코드의 depth를 줄여보시면 좋을거 같아요

2024-11-02 06:02 UTC, yujo11 commented on src/pages/Signup/progresses/ArtistProgress/index.tsx
> +  const [currentStep, setCurrentStep] = useState<1 | 2>(1);
`1`, `2` 대신에 어떤 역할을 하는지 추론할 수 있는 이름을 사용해보시면 좋을거 같아요

2024-11-02 08:40 UTC, yujo11 requested changes

2024-11-02 08:40 UTC, yujo11 commented on package.json
> +  "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
여기 뭔가 align이 어긋난거 같네요 👀

2024-11-02 08:40 UTC, yujo11 commented on src/components/common/ArtistItem/index.tsx
> +        </FollowButton>
요건 서버 요청 없이 프론트엔드에서만 상태를 관리하나요?

2024-11-02 08:40 UTC, yujo11 commented on src/components/common/ArtistItem/index.tsx
> +        </FollowButton>
후에 서버 요청도 할 계획이라면 중복 요청을 막기 위해 loading 같은 상태를 같이 만들어줘도 좋겠네요 ㅎㅎ

2024-11-02 08:40 UTC, yujo11 commented on src/components/common/ProductItem/index.tsx
> +      <Thumbnail ratio="square" src={src} alt={alt} heart={true} />
`Thumbnail` 컴포넌트의 위치가 `common/` 하위인데 `heart` 같은 prop은 일반적으로 생각하는 thumbnail의 영역을 벗어난 부분인거 같아요.

특정한 목적으로 쓰이는거라면 이름을 더 명확하게 해주면 좋을거 같아요 ex) `~~ThumbNail`

2024-11-02 08:40 UTC, yujo11 commented on src/components/common/SearchModal/index.tsx
> +  z-index: 100000;
이런 `z-index`는 애플리케이션이 개발되면서 사용되는 영역이 많아질 수 있는데요. 한 곳에 모아서 관리하면 추후 z-index를 컨트롤하는데 도움이 될거 같네요

ex)

```
const Z_INDEX = {
   Header: 100,
   Modal: 200,
   Dialog: 300
    ...
}
```

2024-11-02 08:40 UTC, yujo11 commented on src/components/common/SearchModal/index.tsx
> +  z-index: 100000;
그리고 10만 같이 무작정 큰 값을 주는 것보다는 적당히 100단위로 그룹을 나눠 관리해보셔도 좋을거 같습니다 ㅎㅎ

2024-11-02 08:40 UTC, yujo11 commented on src/pages/SearchResults/components/ArtWorkContents.tsx
> +    if (selectedOption === '최신순') {
여기서 타입 추론이 정상적으로 이뤄지지 않을 것으로 예상 되는데요. 타입을 만들어서 타입 시스템을 이용할 수 있게 개선해보시면 좋을거 같아요

ex)

```ts
type Options = '최신순' | '가격순' | '제목순'

const [selectedOption, setSelectedOption] = useState<Options>('최신순'); 
```

2024-11-02 08:40 UTC, yujo11 commented on src/pages/SearchResults/components/ArtWorkContents.tsx
> +  const [selectedOption, setSelectedOption] = useState('최신순'); // Default option
요 라인들은 GPT 같은 곳에서 코드를 긁어온 건가요? 주석의 의미를 잘 모르곘네요

2024-11-02 09:48 UTC, seung365 commented on src/components/common/ArtistItem/index.tsx
> +        </FollowButton>
실제 API를 호출할때 tanstack query로 loading을 처리 할까 생각중이긴 합니당

2024-11-02 09:49 UTC, seung365 commented on src/components/common/ProductItem/index.tsx
> +      <Thumbnail ratio="square" src={src} alt={alt} heart={true} />
ThumbNail을 쓰는 경우가 작가 or 작품을 나타내는 용도인데 작품의 경우 ThumbNail위에 heart svg가 들어가서 따로 들어가는 경우 저렇게 prop으로 받았긴 합니다.
차라리 ThumbNail을 2개 만드는게 나을까요?

2024-11-02 09:51 UTC, seung365 commented on src/pages/SearchResults/components/ArtWorkContents.tsx
> +  const [selectedOption, setSelectedOption] = useState('최신순'); // Default option
이 부분 sorting 하는 부분인데 그냥 원래 백엔드로 부터 받았던 배열을 original로 가지고 있고 싶어 gpt한테 물어본 부분이긴 합니다 안쓰는 주석들은 지우겠습니다!

2024-11-03 03:00 UTC, joojjang commented on src/apis/artists/usePostStudentArtist.ts
> +  }
mutation 쓰는 컴포넌트에서 에러 처리를 하지않은 이유는 
해당 컴포넌트의 기능과는 크게 상관없는 부분 때문에 컴포넌트가 복잡해지고 길어진다고 생각했기 때문이고요,  
useMutaion에서 하지 않은 이유는 
axios 에러 처리니까...? 해당 부분 안에서 처리하려고 했기 때문입니다
근데 크게 신경을 쓰고 처리를 한 게 아니긴 한데...  
useMutation에서 처리하려면 onError 쓰라는 말씀이신가요?

2024-11-03 03:21 UTC, joojjang commented on src/apis/instance/index.ts
> +      refetchOnWindowFocus: true,
제가 하던 다른 프로젝트에서 복붙한 거라 크게 신경을 못 썼습니다😅  
필요 없는 건 해제하고 필요한 건 추가하겠습니다

2024-11-03 03:37 UTC, joojjang commented on src/pages/Signup/progresses/ArtistProgress/index.tsx
> +  const [currentStep, setCurrentStep] = useState<1 | 2>(1);
그렇게 할까 생각도 해봤는데, 
회원가입에 한해서는 역할/기능으로 이름을 정하는 것보다 숫자로 하는 게 진행도 보거나 파일 구분하는 데 더 편리할 것 같아 숫자로 했습니닷

2024-11-03 03:45 UTC, joojjang commented on src/pages/Signup/progresses/ArtistProgress/StudentArtist/StudentArtist1.tsx
> +    }
```
 if (!code) {
    return;
  }
  ```
  이걸 먼저 하라는 말씀이실까요??

2024-11-03 04:01 UTC, joojjang commented
처음에 리뷰 주신 부분에서 퍼널 적용하는 것 빼고 모두 반영했습니다 ;)

2024-11-03 07:58 UTC, seung365 commented on src/components/common/ArtistItem/index.tsx
> +        </FollowButton>
멘토님 혹시 팔로우 팔로잉 여부를 판단하는 과정에서

로그인한 유저의 팔로우한 아티스트 목록을 조회한다. <- 백엔드 api가 이거 하나만 존재하는데

팔로우한 목록을 어차피 mypage에서도 보여줄 예정이라 이를 tanstack query를 통해 캐싱하고 

팔로우/ 팔로잉 여부를 UI에 보여줄때 캐싱 데이터를 바탕으로 artist id가 팔로우 되어있는지 비교하는 과정을 통해 보여주는게 나을까요?

아님 따로 팔로우 팔로잉 여부만 판단하는 api를 추가하는게 나을까요? (이 부분은 아마 백엔드와 추가적인 협의가 필요한 상황 입니다)

2024-11-04 10:35 UTC, yujo11 commented on src/apis/artists/usePostStudentArtist.ts
> +  }
아니요 그런 의미는 아니었습니다 ㅎㅎ

여러 선택지 중에 여기에서 에러를 처리한 이유가 궁금해 드렸던 질문이었어요

2024-11-04 10:35 UTC, yujo11 commented on src/pages/Signup/progresses/ArtistProgress/StudentArtist/StudentArtist1.tsx
> +    }
네네 맞아요

2024-11-04 10:36 UTC, yujo11 commented on src/components/common/ArtistItem/index.tsx
> +        </FollowButton>
좋습니다 👍  이런 내용은 TODO 주석으로 남겨뒀다가 챙기셔도 좋을거 같네요 ㅎㅎ

2024-11-04 10:38 UTC, yujo11 commented on src/components/common/ProductItem/index.tsx
> +      <Thumbnail ratio="square" src={src} alt={alt} heart={true} />
그런 용도라면 명시적으로 `heart`를 받는 대신에 Thumbnail의 특정 영역을 커스텀 할 수 있게 열어주는 것도 방법일거 같아요

ex)

```tsx
<Thumbnail>
   <img ~ />
   <Thumbnail.Footer>{heart}</Thumbnail.Footer> // <-  <Thumbnail.Footer> 로 전달되었을 때만 Thumbnail 하단 영역에 render
</Thumbnail>
```

2024-11-04 10:39 UTC, yujo11 commented on src/components/common/ProductItem/index.tsx
> +      <Thumbnail ratio="square" src={src} alt={alt} heart={true} />
👆 꼭 이렇게 하라는건 아니고 이런 방법도 있다고 말씀드리는거니 승범님이 고민해보시고 적절한 방법을 골라 적용해보시면 좋겠네요 ㅎㅎ

2024-11-04 10:41 UTC, yujo11 approved these changes
if (!code) {
    return;
  }
이렇게 인푹값이 없을 시 함수가 실행되지 않도록 밸리데이션을 했는데,
사실 인풋값이 없으면 버튼 자체가 disabled되어 실행되지 않습니다.
근데 이런 식으로 밸리데이션을 2차적으로 하는 게 안정성 면에서 좋은 걸까요,
아니면 중복이니까 굳이 할 필요 없는 걸까요?

---

이건 상황에 따라 달라질거 같은데요

code와 상관없이 이후 로직이 진행되는 경우라면 validation을 생략해도 좋을거 같아요.

하지만 방어로직(`if (!code)`)이후에 진행되는 로직에서 code가 필수적인 값이고, 그에 따라 type을 좁히거나 할 필요가 있다면 방어로직이 타입을 좁히는 용도로 유효하게 사용될 수 있을거 같네요

---

이번 주도 고생 많으셨습니다 ~~ 👍 👍 👍

2024-11-04 10:41 UTC, merged