[10주차] 9조 FE 코드리뷰 7회차
kakao-tech-campus-2nd-step3/Team9_FE pull request #87
Opened 2024-11-08 13:35 UTC by seung365

## **PR**

### ✨ 작업 내용

-

---

### 📌 참고 사항

-

---

### 🐞 현재 버그

-

---

### 🧐 질문

-

---

### ✏ Git Close

2024-11-09 08:17 UTC, yujo11 requested changes
안녕하세요 이번 주도 고생 많으셨습니다 ~

에러가 발생할 때는 에러 메세지에 주목해서 하나씩 따라가보면 좋은데요

<img width="549" alt="image" src="https://github.com/user-attachments/assets/d2685281-aeae-4f0e-ac2c-70156324dbe2">

현재 `data.pages`가 타입이 추론되지 않고 있고 useGetFeed를 확인해보면 아래와 같이 data가 void 형식으로 추론되는 걸 확인할 수 있는데요

<img width="651" alt="image" src="https://github.com/user-attachments/assets/eebe2efb-fd7a-4aad-9601-3735141edf57">

따라서 useGetFeed에 들어가보면 여기 역시 반환 타입 추론이 제대로 되지 않는걸 확인할 수 있습니다 

<img width="681" alt="image" src="https://github.com/user-attachments/assets/784ddf1b-76c0-45d9-a94f-4a9c1a503a16">


이 부분을 수정해보시면 좋을거 같네요

2024-11-09 08:17 UTC, yujo11 commented on src/apis/products/useGetFeed.ts
> +      throw new Error('알 수 없는 오류입니다.');
여기에서 throw 한 error는 어디에서 catch 하나요?

2024-11-09 08:17 UTC, yujo11 commented on src/apis/users/useDeleteFollow.ts
> +    },
이 부분이 반복되는 걸로 보이는데 반복되는 코드를 줄여볼 수 있을까요?

2024-11-09 08:17 UTC, yujo11 commented on src/apis/users/useGetFollow.ts
어디에서는 fetch  로직을 가지고 있는데서 error 처리를 하고, 어디에서는 react-query를 사용한 hook에서 에러 처리를 하고 있고, 여기에서는 error 처리를 하지 않고 있는데요. 

전체적으로 코드의 일관성을 지키면서 에러 핸들링 하는 방법에 대해 고민해보시면 좋을거 같아요

2024-11-09 08:17 UTC, yujo11 commented on src/apis/users/useGetFollow.ts
> +    queryKey: ['followList'],
이런 queryKey도 상수화 해두면 나중에 invalidQueries 같은 로직을 통해 data를 refetch 해올 때 용이할거 같네요

2024-11-09 08:17 UTC, yujo11 commented on src/apis/users/useGetUser.ts
> +};
getUsers를 하는 함수와 getArtists를 하는 함수를 분리해서 선언하고 사용하는 곳에서 상황에 맞게 사용할 수 있도록 만들어보셔도 좋을거 같네요

2024-11-09 08:17 UTC, yujo11 commented on src/components/common/CategoryTabBar/index.tsx
> +          isActive={onActive === category}
tabState 그대로 `onActive` state에 들어가고 있는거 같은데 아래처럼 작성해보는건 어떨까요?

```suggestion
          isActive={tabState === category}
```

2024-11-09 08:17 UTC, yujo11 commented on src/pages/Discover/index.tsx
> +        <Suspense fallback={<>Loading...</>}>
👍 👍 👍

2024-11-09 08:17 UTC, yujo11 commented on src/pages/My/components/UserProfileBox.tsx
> +          {' '}
여긴 의도적으로 공백을 넣으신 부분인가요? 코드의 의도 전달이 잘 되지 않아 공백문자를 대신해서 사용하셔도 좋을거 같네요

2024-11-09 08:17 UTC, yujo11 commented on src/pages/My/index.tsx
> +  }
일관되게 Suspense를 이용해 로딩 처리가 되도록 구현해보셔도 좋을거 같네용

2024-11-10 04:58 UTC, joojjang commented on src/apis/users/useGetFollow.ts
둘이서 나눠서 하다보니 서로 스타일이 달랐는데, 리팩토링 해보겠습니다 :)

2024-11-10 06:32 UTC, seung365 commented on src/apis/users/useGetUser.ts
> +};
아 넵 이부분 저도 처음에는 분리했는데 User 정보가 둘 중 하나라 하나로 처리해보긴 했습니다.
좀 어색하다고 느끼신거 같아 다시 분리하겠습니다!

2024-11-10 08:01 UTC, joojjang commented
질문 드렸던 타입 오류 덕분에 고쳤습니다!

그리고
getFeed 함수에서 throw하는 에러는 useGetFeed에서 서스펜스가 캐치하고, 이를 ErrorBoundary로 전달해서 폴백으로 처리하는 로직을 구상했는데  
<img width="431" alt="image" src="https://github.com/user-attachments/assets/b3029885-11bd-4aa6-a191-ce8bc6cae926">
<img width="763" alt="image" src="https://github.com/user-attachments/assets/ad9c4aa3-4f66-4064-9d45-b80504858289">

화면이랑 콘솔이 이렇게 뜨는 걸 보면.. 에러 바운더리로 잘 처리된 게 맞는 걸까요?..  
gpt한테 물어보니까 
> ErrorBoundary는 전체 컴포넌트 트리에 영향을 미쳐서, 에러가 발생하면 해당 범위 내의 모든 UI를 fallback UI로 교체합니다.  
즉, Suspense 내부에서 에러가 발생하면 ErrorBoundary가 fallback UI로 전체 화면을 덮어버릴 수 있습니다.

즉 에러가 처리되기 전까지 전체 화면에 아무 것도 뜨지 않고 폴백 UI만 뜬다... 로 이해하는 게 맞을까요..?

정리하자면 궁금한 게 두 가지입니다.  
1. getFeed에서의 에러가 Discover에서 에러바운더리로 처리가 잘 된 게 맞는 건지,
2. 에러가 나면 에러바운더리로 감싸진 부분만 폴백 ui로 대체되는 게 아니라 전체 화면이 대체되는 게 맞는 건지 (저는 에러가 나더라도 에러바운더리 밖에 있는 SearchBar는 보여야되는 거 아닌가 싶은데..)  

근데 생각해보니 폴백으로 준 'Error' 글자도 안 떠서 그냥 제대로 처리 안 된 것 같네요...

2024-11-10 10:03 UTC, seung365 commented
> 질문 드렸던 타입 오류 덕분에 고쳤습니다!
> 
> 그리고 getFeed 함수에서 throw하는 에러는 useGetFeed에서 서스펜스가 캐치하고, 이를 ErrorBoundary로 전달해서 폴백으로 처리하는 로직을 구상했는데 <img alt="image" width="431" src="https://private-user-images.githubusercontent.com/91789311/384668725-b3029885-11bd-4aa6-a191-ce8bc6cae926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzMwMjMsIm5iZiI6MTczMTIzMjcyMywicGF0aCI6Ii85MTc4OTMxMS8zODQ2Njg3MjUtYjMwMjk4ODUtMTFiZC00YWE2LWExOTEtY2U4YmM2Y2FlOTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5NTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYTUyM2QyMmZjOWEzNTEyY2MxOWI4MzVjYzVkNWEwYzU3MDRkYzMyYmQyOTQwNGFlMGNhM2MwZmNjMDNiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YRIL3eI-7JxeC3DLiDyO6IXFXjlUCcBvhnUexXkTFq4"> <img alt="image" width="763" src="https://private-user-images.githubusercontent.com/91789311/384669301-ad9c4aa3-4f66-4064-9d45-b80504858289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzMwMjMsIm5iZiI6MTczMTIzMjcyMywicGF0aCI6Ii85MTc4OTMxMS8zODQ2NjkzMDEtYWQ5YzRhYTMtNGY2Ni00MDY0LTlkNDUtYjgwNTA0ODU4Mjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5NTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMjJhMWViZTRkMWVmZmIzOTQ3NDkxYjE5ZTQ3YWU1MGI5NWUwOGQyYTg0ZDZjZjI2ZmVlNDQzMzEyZjhjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LgLx2ic8LFf2HpTapO_GLR2v06ZlnPq-mykYHVA0Htk">
> 
> 화면이랑 콘솔이 이렇게 뜨는 걸 보면.. 에러 바운더리로 잘 처리된 게 맞는 걸까요?.. gpt한테 물어보니까
> 
> > ErrorBoundary는 전체 컴포넌트 트리에 영향을 미쳐서, 에러가 발생하면 해당 범위 내의 모든 UI를 fallback UI로 교체합니다.
> > 즉, Suspense 내부에서 에러가 발생하면 ErrorBoundary가 fallback UI로 전체 화면을 덮어버릴 수 있습니다.
> 
> 즉 에러가 처리되기 전까지 전체 화면에 아무 것도 뜨지 않고 폴백 UI만 뜬다... 로 이해하는 게 맞을까요..?
> 
> 정리하자면 궁금한 게 두 가지입니다.
> 
> 1. getFeed에서의 에러가 Discover에서 에러바운더리로 처리가 잘 된 게 맞는 건지,
> 2. 에러가 나면 에러바운더리로 감싸진 부분만 폴백 ui로 대체되는 게 아니라 전체 화면이 대체되는 게 맞는 건지 (저는 에러가 나더라도 에러바운더리 밖에 있는 SearchBar는 보여야되는 거 아닌가 싶은데..)
> 
> 근데 생각해보니 폴백으로 준 'Error' 글자도 안 떠서 그냥 제대로 처리 안 된 것 같네요...

const FeedContent = () => {
  const { data, fetchNextPage, hasNextPage } = useGetFeed();

  const handleScroll = () => {
    const { scrollTop, scrollHeight, clientHeight } = document.documentElement;
    if (scrollTop + clientHeight >= scrollHeight - 100 && hasNextPage) {
      fetchNextPage();
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, [fetchNextPage, hasNextPage]);

  return (
    <ImageGrid>
      {data?.pages.map((page) =>
        page.products.map((product: Product) => (
          <ImageItem key={product.id}>
            <img src={product.thumbnailUrl} alt={product.name} />
          </ImageItem>
        )),
      )}
    </ImageGrid>
  );
};

const Discover = () => {
  return (
    <Wrapper>
      <SearchBar />
      <ContentWrapper>
        <ErrorBoundary fallback={<>Error</>}>
          <Suspense fallback={<>Loading...</>}>
            <FeedContent />
          </Suspense>
        </ErrorBoundary>
      </ContentWrapper>
    </Wrapper>
  );
};

이런식으로 밖에서 감싸면 수정될꺼 같아 남겨요!

2024-11-11 10:23 UTC, yujo11 approved these changes
고생 많으셨습니다~ 소소한 코멘트 하나 남겼는데 확인해보시면 좋을거 같아요 ㅎㅎ

2024-11-11 10:23 UTC, yujo11 commented on src/apis/artists/useGetArtist.ts
> +  });
`options`를 사용하는 곳에서 넣을 수 있게 하면 더 유연하게 사용이 가능할거 같네요

2024-11-11 10:23 UTC, yujo11 commented on src/apis/artists/useGetArtist.ts
> +  });
react-query v5 에서는 queryOptions 같은걸 사용해서 option만 추상화해서 사용하는 방법도 많이들 사용하는거 같아요 참고 하시면 좋겠네요 ㅎㅎ

2024-11-11 10:23 UTC, merged